### ISSUE TITLE
PowerShell (PoSh) is available on all recent microsoft OS

### ISSUE THREAD

**Issue by so0k** [batsh-dev-team/Batsh#26]
Wouldn't it be better to compile to PoSh over Batch?

**Comment by dumblob** [comment]
>Every non-essential part of the system is uninstalled, so all I can rely on is batch.)

@cromo just curious - was also the visual basic interpreter uninstalled or available? I always thought, that visual basic is lingua franca on Windows and Batch is just a very poor neighbor. I also think, that visual basic can't be uninstalled and given it's capabilities it's way faster and easier to compile to. Not speaking about it's power to do absolutely anything in windows (basically all existing APIs on Windows are exposed in visual basic IIRC).
